#### `E0203`: ReturnOutsideFunction

A `yeet` statement was used outside of a function

Erroneous code example:
```
// error!
fun main() -> int {}
yeet 0;
```

To fix this error, ensure that the `yeet` statement is placed inside a function. Example:

```
// ok!
fun main() -> int {
    yeet 0;
}
```
